import React from 'react';

function About() {
    return (
        <div className="container my-5">
            {/* About Title */}
            <h2 className="text-center mb-4 text-primary">About the Utah Jazz</h2>
            <p className="lead text-center mb-4 text-muted">
                The Utah Jazz is a professional basketball team based in Salt Lake City, Utah.
                Founded in 1974, the team has had a storied history and become one of the
                premier franchises in the NBA. With numerous playoff appearances and legendary
                players over the years, the Jazz continue to excite fans with their dynamic
                style of play.
            </p>

            {/* Utah Jazz Legends Title */}
            <h4 className="text-center mb-3 text-success">Utah Jazz Legends</h4>
            <p className="text-center mb-5 text-muted">
                Over the years, the Utah Jazz have been graced by some of the greatest players
                in NBA history. Here are a few legendary figures who have shaped the franchise's
                legacy:
            </p>

            {/* Legends Section (Cards) */}
            <div className="row row-cols-1 row-cols-md-3 g-4">
                {/* John Stockton Card */}
                <div className="col">
                    <div className="card shadow-lg border-light rounded">
                        <img
                            src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/John_Stockton_1988-89.jpg/640px-John_Stockton_1988-89.jpg"
                            alt="John Stockton"
                            className="card-img-top rounded-circle mb-3 img-fluid"
                            style={{ width: '250px', height: '250px', objectFit: 'cover', margin: '0 auto' }}
                        />
                        <div className="card-body text-center">
                            <h5 className="card-title">John Stockton</h5>
                            <p className="card-text text-muted">Hall of Fame Point Guard, NBA assists leader.</p>
                        </div>
                    </div>
                </div>

                {/* Karl Malone Card */}
                <div className="col">
                    <div className="card shadow-lg border-light rounded">
                        <img
                            src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Karl_Malone_1988-89.jpg/640px-Karl_Malone_1988-89.jpg"
                            alt="Karl Malone"
                            className="card-img-top rounded-circle mb-3 img-fluid"
                            style={{ width: '250px', height: '250px', objectFit: 'cover', margin: '0 auto' }}
                        />
                        <div className="card-body text-center">
                            <h5 className="card-title">Karl Malone</h5>
                            <p className="card-text text-muted">Power Forward, 14-time NBA All-Star.</p>
                        </div>
                    </div>
                </div>

                {/* Donovan Mitchell Card */}
                <div className="col">
                    <div className="card shadow-lg border-light rounded">
                        <img
                            src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Donovan_Mitchell_makes_underhanded_layup_around_Alex_Len_in_2018_%28crop%29.jpg/640px-Donovan_Mitchell_makes_underhanded_layup_around_Alex_Len_in_2018_%28crop%29.jpg"
                            alt="Donovan Mitchell"
                            className="card-img-top rounded-circle mb-3 img-fluid"
                            style={{ width: '250px', height: '250px', objectFit: 'scale', margin: '0 auto' }}
                        />
                        <div className="card-body text-center">
                            <h5 className="card-title">Donovan Mitchell</h5>
                            <p className="card-text text-muted">Dynamic Shooting Guard, rising NBA star.</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* The Future Section */}
            <h4 className="text-center mt-5 text-primary">The Future of the Utah Jazz</h4>
            <p className="text-center mb-5">
                The Utah Jazz are building a new generation of stars, with players like Lauri Markkanen and Walker Kessler
                leading the charge. With a strong foundation and passionate fanbase, the team is poised for future success.
            </p>

            {/* Note Section */}
            <h5 className="text-center mt-5 text-info">Note</h5>
            <p className="text-center text-muted">
                This website was created as a project for my databases class. The content on this about page was generated by AI.
                The website is for learning purposes, and is not intended for commercial use. The images are from Wikimedia Commons.
            </p>
        </div>
    );
}

export default About;
